### PR TITLE
Clarify how one would use this package

### LINKED ISSUE #128: @azure/ms-rest-azure-js - can this repo get archived and a note added to the npm package about maintenance
Can the @azure/ms-rest-azure-js [npm page](https://www.npmjs.com/package/@azure/ms-rest-azure-js) and the associated GitHub repo have some kind of text that indicates this shouldn't be the users first choice when considering Azure auth libraries? 

Include links to the correct libraries please.

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #128

As discussed in #128, it is not clear when one would need to use this package. This PR attempts to add clarification in this area

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
cc @diberry

**Review by daviwil — APPROVED** [review]

**Comment by diberry** [comment]
Looks good. Thank you.

**Review by joheredi — APPROVED** [review]
Looks good!

**Comment by ramya-rao-a** [comment]
Closing in favor of #131

**Pull request closed without merging**
